### ISSUE TITLE
Sync tests

### ISSUE THREAD

**Issue by kenchris** [kenchris/urlpattern-polyfill#106]
Use the new ignoreCase tests from https://github.com/web-platform-tests/wpt/commit/6d152e4018ca4f45ce93eea4985c516a518c3ad6 and replace the existing ones

**Comment by kenchris** [comment]
Tests have been synced and one test failed, but that has been followed by following the ctor steps in the spec carefully. @wanderview

**Comment by wanderview** [comment]
Thanks!
