### ISSUE TITLE
Implement "inherit left, wildcard right" behavior from whatwg/urlpattern#198

### ISSUE THREAD

**Issue by jeremyroman** [kenchris/urlpattern-polyfill#122]
whatwg/urlpattern#198 proposes some changes to the URLPattern syntax to make it more convenient in cases where more than one component is of interest, and/or a base URL is used. If it is merged, urlpattern-polyfill should follow suit.

I have a PR ready for that.

**Comment by jeremyroman** [comment]
The upstream whatwg/urlpattern#198 is now merged.

**Comment by kenchris** [comment]
Awesome, I will have a look at the PR tomorrow.
