### ISSUE TITLE
implement URLPattern.compareComponent()

### ISSUE THREAD

**Issue by wanderview** [kenchris/urlpattern-polyfill#28]
The c++ native implementation now has a URLPattern.compareComponent() static method.  See:

* https://bugs.chromium.org/p/chromium/issues/detail?id=1232795
* https://github.com/WICG/urlpattern/issues/61

This part of the API is not as stable as the rest and may still change.  I'm not going to have time to add this to the polyfill immediately.

Note, this will depend on #27.

**Comment by kenchris** [comment]
This has been implemented and will be shipping in 8.0.0
