### ISSUE TITLE
Invalid `main` in package.json

### ISSUE THREAD

**Issue by zachleat** [kenchris/urlpattern-polyfill#38]
```
Error: Cannot find module '/Users/zachleat/Code/eleventy/node_modules/urlpattern-polyfill/dist/index.cjs'. Please verify that the package.json has a valid "main" entry
```

I don’t see an index.cjs in the dist folder locally on `rc1`—did I miss something?

**Comment by jeffposnick** [comment]
I think that the reference to a `.cjs` file comes from the instructions at https://github.com/developit/microbundle#-installation--setup--, but that info is out of date.

The `main` field should probably be set to the `.umd.js` file, as shown in the example a little bit further down the page.

**Comment by Paso** [comment]
A quick work around is to import the specific file manually. 

eg. `import { URLPattern } from 'urlpattern-polyfill/dist/index.umd';`
