### ISSUE TITLE
Publish Version with "types" field

### ISSUE THREAD

**Issue by nnnnathann** [kenchris/urlpattern-polyfill#44]
Hi,

The version published on NPM under the tag 1.0.0-rc1 doesn't have the "types" field in package.json making typescript integration awkward

I wonder if it would be possible to publish a new version from main?

Thank you!
nathan

**Comment by TechQuery** [comment]
I fix this with `1.0.0-rc.5`.

**Comment by nnnnathann** [comment]
Thank you
