### ISSUE TITLE
Polyfill example

### ISSUE THREAD

**Issue by GrosSacASac** [kenchris/urlpattern-polyfill#47]
urlpattern.js
```js
if (!globalThis.URLPattern) {
    const URLPatternModule = await import("urlpattern-polyfill/dist/index.umd.js");
    const { URLPattern } = URLPatternModule.default;
    globalThis.URLPattern = URLPattern;
}
```

main source file
```js
import "./urlpattern.js";
```

**Comment by justinfagnani** [comment]
It'd also be great to vend an entrypoint that does the feature detection and global patching for you.

**Comment by kenchris** [comment]
Yes, my motion sensor polyfill does something like that, e.g. it returns the native implementation if it exists or else the polyfilled version:

```js
export const RelativeOrientationSensor = window.RelativeOrientationSensor ||
class RelativeOrientationSensor extends DeviceOrientationMixin(Sensor, 'deviceorientation') { ... }
```
https://github.com/kenchris/sensor-polyfills/blob/master/src/motion-sensors.js#L159

Would something like that be useful? What do you think @wanderview ?

**Comment by abdonrd** [comment]
Any news on this? Thanks!

**Comment by kenchris** [comment]
I am OK with this, so want to do a PR @abdonrd ? 

@justinfagnani I didn't follow what you meant with "vend an entrypoint"?

**Comment by kenchris** [comment]
We cannot support this for CJS due to top-level await, but we could support it for ESM

**Comment by kenchris** [comment]
I have a tentative solution to this: https://github.com/kenchris/urlpattern-polyfill/pull/71

**Comment by kenchris** [comment]
This has now been committed, thanks to @justinfagnani for review.

It doesn't use dynamic import, as that seems a user concern. As Justin said it

> I personally think that's a bit of a separate concern. You have potentially three things:
> 
> - Implementation
> - Patching the global
> - Dynamic loading the code
>
> A lot of apps will have their own systems for (3) that ensure that app code is run after polyfills load.
