### ISSUE TITLE
1.0.0-rc2

### ISSUE THREAD

**Issue by fabiancook** [kenchris/urlpattern-polyfill#58]
Hi, the most recent changes make it possible for the package to be imported nicely for esm implementations. 

1.0.0-rc1 is the latest published to npm, which does not have some changes from this repo. 

Will there be a 1.0.0-rc2 in the near future?

**Comment by kenchris** [comment]
Sure, I will try to make a new release soon - maybe tomorrow

**Comment by kenchris** [comment]
It has now been published!

**Comment by fabiancook** [comment]
Perfect! 

This module is now in use here:

https://github.com/virtualstate/app-history/blob/180e2f41a438193cd187529fc8624da7be111354/src/tests/examples/url-pattern.ts#L12-L33
```typescript
appHistory.addEventListener("navigate", ({ destination, transitionWhile }) => {
    return transitionWhile(handler())

    async function handler() {
        const identifiedTest = new URLPattern({
            pathname: "/test/:id"
        });
        if (identifiedTest.test(destination.url)) {
            body.innerHTML = destination.getState<{ innerHTML: string }>().innerHTML;
        } else {
            throw new Error(unexpectedPage);
        }
    }
});

const expectedHTML = `${Math.random()}`;

await appHistory.navigate("/test/1", {
    state: {
        innerHTML: expectedHTML
    }
}).finished;
```
