### ISSUE TITLE
Support ".compile"

### ISSUE THREAD

**Issue by kettanaito** [kenchris/urlpattern-polyfill#68]
Thank you for moving so fast with the `URLPattern`!

I'd like to know if you're planning on supporting a `.compile` method (referring to the [.compile() from `path-to-regexp`](https://github.com/pillarjs/path-to-regexp#compile-reverse-path-to-regexp)). It'd be great to populate a URL pattern with values:

```js
const pattern = new URLPattern('https://:environment.service.com/:service/:resource')

const url = pattern.compile({
  environment: 'staging',
  service: 'v2',
  resource: '/user'
})

url.toString() // "https://staging.service.com/v2/user"
```

**Comment by kettanaito** [comment]
I recall there's been a discussion around this in the design document repo. Please feel free to link to it.

**Comment by kenchris** [comment]
Feature requests should be filed for the spec repo https://github.com/WICG/urlpattern

**Comment by wanderview** [comment]
This is already on file at: https://github.com/WICG/urlpattern/issues/73

**Comment by kettanaito** [comment]
Perfect! Thank you, @kenchris @wanderview!
