### ISSUE TITLE
Update polyfill for URLPattern release candidate

### ISSUE THREAD

**Issue by wanderview** [kenchris/urlpattern-polyfill#7]
The initial release candidate of URLPattern is nearing completion.  There are only 2 remaining CLs to land:

 * https://chromium-review.googlesource.com/c/chromium/src/+/2937293
 * https://chromium-review.googlesource.com/c/chromium/src/+/2951204

As we move toward developer trials of the API it would be great to update the polyfill to match the new proposed API.

Changes to URLPattern since the last update are:

 * Support for a `*` wildcard.
 * Support for applying URL canonicalization to plaintext within a pattern string.
 * Support for a constructor string like `new URLPattern("https://*.example.com/foo/:name")`.
 * Support for passing a second argument to the constructor, test(), and exec() to specify a base URL.
 * Regexes are compiled with the `/u` compile flag.
 * WPT test runner has significantly changed to accommodate new features.
 * Lots of new WPT test cases in the data file.

A number of these features depend on changes to code at the path-to-regexp layer.  To support this in the polyfill I've implemented the same features in a branched fork:

https://github.com/wanderview/path-to-regexp/tree/urlpattern-5-lenient

If/when we get consensus on URLPattern shipping we can then look into possibly merging these back up to path-to-regexp.  For now I think we would want to just include the forked path-to-regexp inline in the polyfill?

Of the various features, implementing the constructor string will probably require the most effort.  It requires writing a parser like in:

https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/url_pattern/url_pattern_parser.cc

The URL canonicalization of patterns may also be a bit tricky.  It may not be possible to exactly match the c++ URLPattern just using the `URL()` API to get at the platform's canonicalizer.  I think we can get pretty close, though.

I can take a stab at implementing a number of these items.  I don't know the npm or build systems well, though.  I'll need help getting the forked path-to-regexp into the polyfill correctly.

@kenchris, WDYT?

**Comment by kenchris** [comment]
Hi there,

This sounds great, I am ready to help and review PRs.

I think we need to publish your fork as a first step.

I guess we could make a @urlpattern project on NPM and then publish under that. like `@urlpattern/path-to-regexp` and `@urlpattern/urlpattern-polyfill` - what do you think about that? Then we will just make a dependency on that project

**Comment by wanderview** [comment]
Hmm, ok.  I was thinking more of just inlining the forked path-to-regexp in the polyfill repo itself for now, but I can investigate publishing the fork.  I'm having trouble logging into npm right now, but will try again later.

**Comment by wanderview** [comment]
I got the organization made I think and sent you an invite.  I need to double-check internally that its ok for me to publish my fork of path-to-regexp there, though.

**Comment by kenchris** [comment]
Sure, sounds good. I accepted

**Comment by wanderview** [comment]
I think its going to be difficult for me to publish my forked path-to-regexp to npm directly.  I was following more of a process for sending the changes upstream via PRs once the spec settles.

**Comment by wanderview** [comment]
I think I have all of the easy stuff taken care of.  Next I need to implement the constructor string parser.  This might take a bit to complete as its a lot of code to translate from c++.

**Comment by wanderview** [comment]
With the merged and pending pull requests the polyfill is now passing all but one of the WPT test cases.

Unfortunately that last test case hits some interop issues between URL canonicalization of hostnames.  Chromium wants to encode `@` in a hostname as `%40`, but the spec and other implementations treat it as invalid.  I'm not sure if I should make chromium URLPattern do an extra check for this or just remove the test case.  Will think on it.

Also, note that I think there is a general weakness in the url canonicalization routines in the polyfill.  While assigning to the URL object's properties can be used to canonicalize, it does not cause any exception to be thrown if the value is invalid.  Instead the URL property just doesn't change.  Not sure if there are other cases of that issue that need to be fixed and we are just lacking test coverage, etc.

**Comment by wanderview** [comment]
Ok.  I decided to drop the test case for now.  This brings the polyfill up to passing the WPT tests.

I think the next steps after merging this stuff would be to figure out the dependency to the path-to-regexp branches and then publish.  I updated a number of my path-to-regexp branches while getting all this to work.  The latest branch to use is:

https://github.com/wanderview/path-to-regexp/tree/urlpattern-6-ascii-regexp

**Comment by wanderview** [comment]
@kenchris I hope you can take these remaining steps to getting it published.  I will be OOO for the next week.

**Comment by kenchris** [comment]
Some merge issues with last patch. Can you look at it before leaving?

**Comment by wanderview** [comment]
I think its fine.  If a later PR was accidentally merged before an earlier PR it ends up bringing in the earlier PR's changes as well.  So all the changes look to be landed in the end.  I'll close the outstanding PR.

**Comment by wanderview** [comment]
Since 1.0.0-rc1 is published I'm going to mark this fixed.
