### ISSUE TITLE
Missing `main` field from package.json causes problem with eslint `node/no-missing-require`

### ISSUE THREAD

**Issue by lachlanhunt** [kenchris/urlpattern-polyfill#75]
After the recent change intended to support CommonJS, the ability to `require("urlpattern-polyfill")` now works, but due to the missing `main` field in package.json pointing to the CJS version, the eslint rule `node/no-missing-require` now complains about the line to `require("urlpattern-polyfill");`.

To fix this, add these lines back to package.json

```
  "main": "./dist/index.cjs",
  "module": "./dist/index.js",
```

I've tested this fix when using CommonJS. I haven't yet tested the fix when using ESM.

**Comment by SanderElias** [comment]
This is probably resolved by the 4.0.0 version. Can you confirm?

**Comment by SanderElias** [comment]
@lachlanhunt We learned a couple of things today about package.json. Check 4.0.1, which will be out shortly.

**Comment by lachlanhunt** [comment]
4.0.1 works, thanks.
