### ISSUE TITLE
refactor to real private class fields

### ISSUE THREAD

**Issue by jimmywarting** [kenchris/urlpattern-polyfill#78]
Switch to using `#` instead?
https://github.com/kenchris/urlpattern-polyfill/blob/ed3c72963fc5fcf55741ea9390c64071f7f8ad44/src/url-pattern-list.ts#L6

**Comment by SanderElias** [comment]
@jimmywarting At this time the private field declarations are not available in all implementations we want to support. While we use TS, we want to keep as close as possible to JS, to keep the polyfill as small as possible

**Comment by jimmywarting** [comment]
You can still use private class fields in ts and set a lower target version when you compile your src to js, it will compile your code to using WeakMap

**Comment by SanderElias** [comment]
@jimmywarting I know, but this does add quite a few lines of code to the polyfill, with a very small payoff. 
In my opinion, that's not worth it.
@kenchris, what's your opinion?

**Comment by kenchris** [comment]
I agree that it is not worth it for now, but we can reevaluate at a later point

**Comment by SanderElias** [comment]
I added the label won't fix it for now and will close this.
If there is a reevaluation about this in the future, we will gladly reopen it!
