### ISSUE TITLE
Type exports are broken and incorrect in v3

### ISSUE THREAD

**Issue by fregante** [kenchris/urlpattern-polyfill#80]
When using a bundler, one is supposed to use:

```js
import "urlpattern-polyfill";
```

But the types are not loaded this way because TypeScript will try to load `urlpattern-polyfill/index.d.ts`:

```
Cannot find module 'urlpattern-polyfill' or its corresponding type declarations.ts
```

This works correctly:

```js
import "urlpattern-polyfill/dist";
```

But then it fails in Node because of the `exports` key in package.json.

---

In short I think you need to set the `types` property in package.json

Additionally, currently there's no way to use the underlying implementation directly without applying a polyfill because:

- there's no `index.impl.d.ts`
- the `index.impl.js` file does not appear in the `exports` map

**Comment by fregante** [comment]
The last part may be fixed by:

- https://github.com/kenchris/urlpattern-polyfill/pull/77

**Comment by SanderElias** [comment]
Can you check V4 when Kenneth has released it to NPM?
it should take care of this. But supporting a wide range of node and typescript versions is euhm, challenging 😉

**Comment by fregante** [comment]
> In short I think you need to set the `types` property in package.json

Still missing.

`exports.main`, `exports.module` and `exports.types` aren't real properties, they shouldn't be part of `exports`
