### ISSUE TITLE
Property 'URLPattern' does not exist on type 'typeof globalThis'

### ISSUE THREAD

**Issue by abdonrd** [kenchris/urlpattern-polyfill#94]
Following the README I have added:

<img width="692" alt="Screenshot 2022-05-12 at 19 55 31" src="https://user-images.githubusercontent.com/1007051/168138662-b247db06-a1ef-4376-9b8d-586065830217.png">

But I have the warning:

>Property 'URLPattern' does not exist on type 'typeof globalThis'

I also have tried to add this to the `compilerOptions` of the `tsconfig.json`:

```
"types": ["urlpattern-polyfill"]
```

**Comment by kenchris** [comment]
Can you try with the latest version (5.0.0)? Not sure it helps but there were some changes to the types

**Comment by abdonrd** [comment]
Still the same with v5.

**Comment by SanderElias** [comment]
Hmm, makes sense. if the polyfill isn't loaded, the type isn't going to be there. It is a bit of a catch-22 with typescript.

@kenchris Perhaps we should update the readme a bit. (see #96, for example)

**Comment by abdonrd** [comment]
Same error with the latest version:
<img width="621" alt="Screenshot 2022-05-25 at 17 32 27" src="https://user-images.githubusercontent.com/1007051/170300713-4cf9e44d-511f-4d1d-83cc-0ecf0774efd8.png">

**Comment by SanderElias** [comment]
@abdonrd What versions are you using for TS and node, and types? Currently, I can not reproduce your issue.

Aside from that, it's safe to ignore this error.  The whole idea of the line is to check if it's there and load it if it is missing.
Add this instead:
```ts
// @ts-ignore: Property 'UrlPattern' does not exist 
if (!globalThis.UrlPattern) {
  await import("urlpattern-polyfill")
}
```

I will also update the readme with this. And update the readme with the same.
Closing this as it seems working as expected. Feel free to keep discussing it here, as there might be something I didn't considder.

**Comment by abdonrd** [comment]
> @abdonrd What versions are you using for TS and node, and types? Currently, I can not reproduce your issue.

TypeScript v4.7.2.
What do you mean with the types?


> Aside from that, it's safe to ignore this error. The whole idea of the line is to check if it's there and load it if it is missing. Add this instead:
> 
> ```ts
> // @ts-ignore: Property 'UrlPattern' does not exist 
> if (!globalThis.UrlPattern) {
>   await import("urlpattern-polyfill")
> }
> ```

Yes, that is what we are using.
