### ISSUE TITLE
Incompatibility due to the nullish coalescing operator

### ISSUE THREAD

**Issue by sneko** [kenchris/urlpattern-polyfill#99]
Hi,

Thank you for the polyfill, it works in latest environments but when dealing with older node versions, babel versions... it may fail to compile due to 1 nullish coalescing operator.

https://github.com/kenchris/urlpattern-polyfill/blob/main/src/url-pattern.ts#L159

I get this kind of error:
```
  const defaultPattern = `[^${escapeString(options.delimiter ?? "/#?")}]+?`;
                                                              ^

SyntaxError: Unexpected token '?'
```

I browsed a lot of topics posted across years I saw like 4-5 fixes to solve this issue. But in my case, since I have a Babel project I just had to update to:
```
    "core-js": "^3.22.8",
```

And in my `babel.config.js`:
```js
module.exports = {
  presets: ['@babel/preset-env'],
};
```

In case you don't have Babel and no easy way to add it you will have to investigate 😄 ...

It's not really an issue, much more something to help in case it happens to someone else (I spent hours on this to find the minimal settings to tweak to make it working).

Thank you,

**Comment by Paso** [comment]
This (the nullish coalescing operator) does so that this library cannot be imported in a project using Webpack 4 as its parser (acorn 6) doesn't (and won't) support the language feature. 

A work-around is using urlpattern-polyfill 4.0.3, before the change was introduced and importing it using ~~`import { URLPattern } from 'urlpattern-polyfill/dist/index';`~~. 
EDIT: Sorry, spoke too soon. In order for it to work in both client and server (for SSR) through webpack 4 I had to use `const { URLPattern } = require('urlpattern-polyfill');`

Would you consider removing the nullish coalescing operator @kenchris ?

**Comment by schonfeld** [comment]
FWIW, I just ran into the same issue, and realized my production node runtime was still on v12. Turns out the ?? operator is supported natively in >= node v15...

https://node.green/#ES2021-features-Logical-Assignment-----basic-support

**Comment by Paso** [comment]
To be clear, the node version is not the problem I have because webpack uses its own parser (acorn).

**Comment by kenchris** [comment]
Yes, I would gladly accept a patch to move away from the nullish coalescing operator. Just make sure to run all the tests before sending the PR

**Comment by SanderElias** [comment]
@kenchris As we are building a polyfill for modern browsers, I don't feel that supporting  _old, unsupported_ nodeJs version should be something we need to do. The LTS support for Node 12 (and below) has passed for quite a while now. Nullish coalescing is supported in [node 14](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V14.md#update-to-v8-81) and above.  And [browsers are supporting](https://caniuse.com/?search=nullish%20coalescing%20operator) this for a long time.

Although it would be a small change, it would feel wrong to me.

**Comment by sneko** [comment]
@SanderElias In my case I struggled a lot to tweak projects so they can deal with the mentioned `??`.

It's not always easy to migrate libraries like `acorn` or so (sometimes impossible, really), and upgrading Node sometimes break some librairies too (that are no longer maintained and not compatible). I understand we need to move forward most of the time, but sometimes migrating a whole project just for a polyfill sounds overkilled. Even when using `babel` in some projects it has been a pain to configure (because it required me some settings too in the underlying framework too).

What I see:
* if the polyfill was using a lot of `??` it would make sense to say "do not change anything"
* but in our case there is **only 1** occurence, leaving the question if it worths the pain for new people trying to adopt the polyfill (knowing that the main idea of the polyfill is to help supporting "old browsers"...)

**Comment by kenchris** [comment]
This is a minor change with little to no impact on maintenance, so if it helps someone, I am OK with it. If it had an impact on maintenance, I would probably feel different

**Comment by SanderElias** [comment]
@kenchris @sneko Fair point.
See #104
